name: wechat_assets_picker
description: An assets' picker written in pure Dart which looks like the one in WeChat, support multi asset pick from the device.
version: 4.1.0+2
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image: ^0.9.0
  flutter_common_exports: ^0.1.0
  photo_manager: ^0.5.7
  provider: ^4.3.1
  video_player: ^0.10.11+2
  image: ^2.1.4
  meta: ^1.1.6
  path: ^1.6.2
  flutter_ffmpeg: ^0.2.10
  video_thumbnail: ^0.2.1
  path_provider: ^1.6.7
  intl: ^0.16.1
  image_cropper: ^1.3.1